# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: 2sVu66uVs1xfAQVIsEMHzTjmeJp9HCtM
    secretKey: AKID0ufDZjkY9YkkPtLgpjPr68wVv89vToCO
    region: ap-beijing
    bucket: study -1326939213
#    host: study-1326939213.cos.ap-beijing.myqcloud.com

spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hula_study_database
    username: root
    password: 909090pppp


    # Redis 配置
    # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 36.140.162.53
    port: 6379
    timeout: 5000
  #    password: 123456

    # Elasticsearch 配置
    # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://36.140.162.53:9200
  #    username: root
  #    password: 123456